config/routes.rb
Rails.application.routes.draw do
  # get 'pages/home'
  root 'pages#home'
  resources :products
  resources :favorites, only: [:create, :destroy]
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
  validates_presence_of :cat_name
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :favorites
  has_many :users, through: :favorites

  validates_presence_of :pro_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :products, through: :favorites

  validates_uniqueness_of :phone_number
  validates_presence_of :full_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :phone_number])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:cat_name)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_product

  def create
    respond_to do |format|
      if Favorite.create(product: @product, user: current_user)
        format.html {redirect_to @product, notice: 'Product has been favorited'}
        format.json { render :show, status: :created, location: @product }
      else
        format.html {redirect_to @product, alert: 'Something went wrong...*sad panda*'}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      Favorite.where(product_id: @product.id, user_id: current_user.id).first.destroy
      format.html {redirect_to @product, notice: 'Product is no longer in favorites'}
      format.json { head :no_content }
    end
  end
  private

  def set_product
    @product = Product.find(params[:product_id] || params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:pro_name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %><br />
    <%= form.text_field :cat_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="tab-content" id="myTabContent" style="padding-left: 20%">
  <div class="tab-pane fade show active" id="grid" role="tabpanel" aria-labelledby="grid-tab">
    <h1 >All Categories</h1>
    <div class="products_section">
      <div class="row">
        <!--        <div class="col-lg-4 col-md-6 col-xs-12">-->
        <table class="col-lg-4 col-md-6 col-xs-12">
          <thead class="product_info2">
          <tr>
            <th><h2>Name</h2></th>
            <th colspan="1"></th>
          </tr>
          </thead>
          <tbody class="product_info2">
          <% @categories.each do |category| %>
            <tr>
              <!--                <div class="product_info2">-->
              <td><%= category.cat_name %></td>
              <td><%= link_to 'Show', category %></td>
              <td><%= link_to 'Edit', edit_category_path(category) %></td>
              <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <!--                </div>-->
            </tr>
          <% end %>
          </tbody>
        </table>
        <!--        </div>-->
      </div>
    </div>
    <!--<br>-->

    <%#= link_to 'New Category', new_category_path %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="product_info2">
  <p>
    <strong style="color: hotpink">Name:</strong>
    <%= @category.cat_name %>
  </p>
  <p>
    <strong style="color: hotpink"><i>Products:</i></strong>
    <% i = 1 %>
    <% @category.products.each do |pro| %><br />
      <%= i.to_s + '- '+ pro.pro_name %>
      <% i +=1 %>
    <%end%>
  </p>
<!--  <%#= link_to 'Edit', edit_category_path(@category) %> |-->
  <%= link_to 'Back', categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>fuzzyumbrella</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Bootstrap-->
    <link  href="http://amplifythemes.com/preview/cartzee/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <script src="http://amplifythemes.com/preview/cartzee/assets/js/bootstrap.min.js"></script>
    <!--Revolution Slider-->
    <link  href="http://amplifythemes.com/preview/cartzee/assets/revolution/css/layers.css" rel="stylesheet" type="text/css">
    <link  href="http://amplifythemes.com/preview/cartzee/assets/revolution/css/navigation.css" rel="stylesheet" type="text/css">
    <link  href="http://amplifythemes.com/preview/cartzee/assets/revolution/css/settings.css" rel="stylesheet" type="text/css">
    <!--font Awesome-->
    <link  href="http://amplifythemes.com/preview/cartzee/assets/css/fontawesome-all.css" rel="stylesheet" type="text/css">
    <!--Owl-Carousel-->
    <link rel="stylesheet" href="http://amplifythemes.com/preview/cartzee/assets/css/owl.carousel.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://amplifythemes.com/preview/cartzee/assets/css/owl.template.min.html" rel="stylesheet" type="text/css">
    <!--Custom Style Sheet-->
    <link  href="http://amplifythemes.com/preview/cartzee/assets/css/style.css" rel="stylesheet" type="text/css">
    <!--Responsive file-->
    <link  href="http://amplifythemes.com/preview/cartzee/assets/css/responsive.css" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <script src="http://amplifythemes.com/preview/cartzee/assets/js/jquery.js"></script>
    <!-- REVOLUTION SLIDER -->
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/jquery.templatepunch.tools.min.html"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/jquery.templatepunch.revolution.min.html"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.actions.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.carousel.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.kenburn.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.layeranimation.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.migration.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.navigation.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.parallax.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.slideanims.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.extension.video.min.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/revolution/js/revolution.initialize.js"></script>
    <!-- REVOLUTION SLIDER SCRIPT -->
    <script src="http://amplifythemes.com/preview/cartzee/assets/js/main-slider-script.js"></script>
    <!-- Carousel SCRIPT -->
    <script src="http://amplifythemes.com/preview/cartzee/assets/js/owl.carousel.js"></script>
    <!-- Custom SCRIPT -->
    <script src="http://amplifythemes.com/preview/cartzee/assets/js/datecounter.js"></script>
    <script src="http://amplifythemes.com/preview/cartzee/assets/js/custom.js"></script>
  </head>

  <body>

  <!-- Start Header -->
  <header class="main_header header-2">
    <div class="container">
      <div class="row">
        <div class="mobile-men-btn" id="responsive_nav">
          <a href="#"><i class="fa fa-bars"></i></a>
        </div>
      </div>
    </div>
    <nav class="header2-nav header3-nav responsive_none">
      <div class="container">
        <ul style="padding-left: 30%">
          <li><%= link_to 'HOME', root_path, class: "active" %></li>
          <li><a href="#">Collections</a>
            <ul>
<!--              <li><a href="products">Products</a></li>-->
              <li><%= link_to 'Products', products_path%></li>
              <li><%= link_to 'Categories', categories_path%></li>
<!--              <li><a href="categories">Categories</a></li>-->
            </ul>
          </li>
          <% if current_user %>
            <li><%= link_to 'Edit Personal info  ', edit_registration_path(current_user)%></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          <%else %>
            <li><%= link_to 'login', new_user_session_path %></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
<!--          <li><a href="#">login</a></li>-->
<!--          <li><a href="#">Register</a></li>-->
          <%end %>
        </ul>
      </div>
    </nav>
  </header>

  <!-- End Header -->
    <%= yield %>
    <!-- Main Footer -->
    <footer class="main-footer">
      <div class="container">
        <div class="footer_widget">
          <div class="row">

            <div class="col-lg-3 col-md-6 col-xs-12">
              <h4 class="widget-title">Contact Us</h4>
              <ul class="widget-link">
                <li><a href="#"><span>Office:</span> 12 Fake Street,New York</a></li>
                <li><a href="#"><span>Phone:</span> (08) 8827 633354</a></li>
                <li><a href="#"><span>Fax:</span> 08) 08 4752 1499</a></li>
                <li><a href="#"><span>Mail:</span> support.goaltemplate.com</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer_btm">
          <p>© 2019 <span>fuzzyumbrella</span> by <span>Samar/fuzzyumbrella</span>. All Rights Reserved.</p>
        </div>
      </div>
    </footer>
    <!-- End Footer -->
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from amplifythemes.com/preview/cartzee/index5.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 03 Feb 2019 20:54:23 GMT -->
<head>
  <title>fuzzyumbrella</title>
</head>

<body>
<div class="clearfix"></div>
<!-- Start Seller Tabs -->
<section style="padding-left: 15%" class="section_padding pb-0">
  <div class="container">
    <div class="row">

      <div class="col-md-9 col-xs-12 p-0">
        <div class="carousel_slider pb-5">
          <div class="col-12">
            <div class="category_carousel owl-carousel owl-template owl-loaded owl-drag">



              <div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-5775px, 0px, 0px); transition: all 4s ease 0s; width: 12375px;"><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="mens_bag">
                  <div class="bag_details text-left">
                    <h1>men’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="womens_bag">
                  <div class="bag_details text-center">
                    <h1>Women’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="womens_bag">
                  <div class="bag_details text-center">
                    <h1>Women’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="mens_bag">
                  <div class="bag_details text-left">
                    <h1>men’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item" style="width: 825px;"><div class="item">
                <div class="womens_bag">
                  <div class="bag_details text-center">
                    <h1>Women’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item" style="width: 825px;"><div class="item">
                <div class="mens_bag">
                  <div class="bag_details text-left">
                    <h1>men’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item" style="width: 825px;"><div class="item">
                <div class="womens_bag">
                  <div class="bag_details text-center">
                    <h1>Women’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned active" style="width: 825px;"><div class="item">
                <div class="mens_bag">
                  <div class="bag_details text-left">
                    <h1>men’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="womens_bag">
                  <div class="bag_details text-center">
                    <h1>Women’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="womens_bag">
                  <div class="bag_details text-center">
                    <h1>Women’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div><div class="owl-item cloned" style="width: 825px;"><div class="item">
                <div class="mens_bag">
                  <div class="bag_details text-left">
                    <h1>men’s</h1>
                    <h2>Bag</h2>
                  </div>
                </div>
              </div></div></div></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>
          </div>
        </div>
        <div class="sidebar_products pb-5">
          <div class="border_outer border_0">
            <div class="container">
              <div class="row">
                <div class="title col-md-12">
                  <h1>Collections</h1>

                </div>
                <div class="col-md-8">
                  <div class="shop-item shop1">
                    <div class="product_info">
                      <h1>Design <br> Collections</h1>

                    </div>
                  </div>
                  <div class="shop-item shop3">
                    <div class="product_info white left">
                      <h1>Jeans <br> Collections</h1>
                      <p>2019</p>
                    </div>
                  </div>
                  <div class="shop-item shop5">
                    <div class="inner_content">
                      <div class="product_info blue">
                        <h1>Women's</h1>
                        <p>Shoes</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="shop-item shop2">
                    <div class="product_info blue center">
                      <h1>Women's</h1>
                      <p>Shirts</p>
                    </div>
                  </div>
                  <div class="shop-item shop4">
                    <div class="product_info white center">
                      <h1>Bags</h1>
                      <p>New Collections</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</section>
<!-- Start Shop Banner -->
<div class="section_padding our_brands">
  <div class="container">
    <div class="brand_carousel owl-carousel owl-template">
      <div class="item">
        <a href="#"><img src="http://amplifythemes.com/preview/cartzee/assets/images/brands/brand1.png" alt="img"></a>
      </div>
      <div class="item">
        <a href="#"><img src="http://amplifythemes.com/preview/cartzee/assets/images/brands/brand2.png" alt="img"></a>
      </div>
      <div class="item">
        <a href="#"><img src="http://amplifythemes.com/preview/cartzee/assets/images/brands/brand3.png" alt="img"></a>
      </div>
      <div class="item">
        <a href="#"><img src="http://amplifythemes.com/preview/cartzee/assets/images/brands/brand4.png" alt="img"></a>
      </div>
      <div class="item">
        <a href="#"><img src="http://amplifythemes.com/preview/cartzee/assets/images/brands/brand5.png" alt="img"></a>
      </div>
      <div class="item">
        <a href="#"><img src="http://amplifythemes.com/preview/cartzee/assets/images/brands/brand6.png" alt="img"></a>
      </div>
    </div>
  </div>
</div>
<!-- End Shop Banner -->
</body>


<!-- Mirrored from amplifythemes.com/preview/cartzee/index5.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 03 Feb 2019 20:54:24 GMT -->
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %><br />
    <%= form.text_field :pro_name %>
  </div>

  <div class="field">
    <%= form.label :price %><br />
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="tab-content" id="myTabContent" style="padding-left: 20%">
  <div class="tab-pane fade show active" id="grid" role="tabpanel" aria-labelledby="grid-tab">
    <h1>All Products</h1>
    <div class="products_section">
      <div class="row">
<!--        <div class="col-lg-4 col-md-6 col-xs-12">-->
          <table class="col-lg-4 col-md-6 col-xs-12">
            <thead class="product_info2">
            <tr>
              <th><h2>Name</h2></th>
              <th><h2>Price</h2></th>
              <th colspan="1"></th>
            </tr>
            </thead>
            <tbody class="product_info2">
          <% @products.each do |product| %>
              <tr>
<!--                <div class="product_info2">-->
                  <td><%= product.pro_name %></td>
                  <td style="color: #ec96af;"><%= '$' + product.price.to_s %></td>
                  <td><%= link_to 'Show', product %></td>
                  <td><%= link_to 'Edit', edit_product_path(product) %></td>
                  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <%if current_user %>
                  <%- unless current_user.favorites.exists?(id: product.id) -%>
                    <td><%= link_to 'Add to favorites', favorites_path(product_id: product), method: :post %></td>
                  <%- else -%>
                    <td><%= link_to 'Remove from favorites', favorite_path(product), method: :delete %></td>
                  <%- end -%>
                <%end %>
<!--                </div>-->
              </tr>
          <% end %>
            </tbody>
          </table>
<!--        </div>-->
      </div>
    </div>
<!--<br>-->

<%#= link_to 'New Product', new_product_path %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="product_info2">
  <p>
    <strong style="color: hotpink">Name:</strong>
    <%= @product.pro_name %>
  </p>

  <p>
    <strong >Price:</strong>
    <i style="color: #ec96af;"><%='$' + @product.price.to_s%></i>
  </p>
  <p>
    <strong style="color: hotpink">Categories:</strong>
    <% i = 1 %>
    <% @product.categories.each do |cat| %><br />
      <%= i.to_s + '- '+ cat.cat_name %>
      <% i +=1 %>
    <%end%>
  </p>
<!--  <%#= link_to 'Edit', edit_product_path(@product) %> |-->
  <%= link_to 'Back', products_path %>
</div>